/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vi.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.vi.domain.Message;
import com.vi.domain.Users;
import com.vi.service.imp.MessageServiceImp;
import com.vi.service.imp.UsersServiceImp;
import com.vi.service.inter.MessageServiceInter;
import com.vi.service.inter.UsersServiceInter;
import com.vi.struts.form.MessageForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-18-2015
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class GoPublishMessageUIAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private String getter;
	public String getGetter() {
		return getter;
	}
	public void setGetter(String getter) {
		this.getter = getter;
	}
	public ActionForward publishMessage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//获取表单
		MessageForm messageForm=(MessageForm) form;
		//创建一个message对象
		Message message=new Message();
		message.setContent(messageForm.getContent());
		UsersServiceInter usersServiceInter=new UsersServiceImp();
		getter=request.getParameter("getter");
		System.out.println("接收人的名字是"+getter);
		message.setGetter(usersServiceInter.getUser(getter));
		message.setMesTime(new Date());
		message.setSender((Users)request.getSession().getAttribute("userInfo"));
		System.out.println("接收人的名字是"+getter);
		usersServiceInter.save(message);
		return mapping.findForward("ok");
	}
	public ActionForward goPublishMessageUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goPublishMessageUi");
	}
}