/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vi.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.vi.domain.Users;

import com.vi.service.imp.UsersServiceImp;
import com.vi.service.inter.UsersServiceInter;
import com.vi.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2015
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
	
		//清空session
		request.getSession().invalidate();
		return mapping.findForward("goLoginUi");
		
	}
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UserForm userForm=(UserForm)form;
		Users user=new Users();
		user.setPassword(userForm.getPassword());
		user.setUserId(Integer.parseInt(userForm.getUserId()));
		//这里直接使用对象开发有一定耦合性（web层与业务层有一定耦合）
		//UsersServiceImp usersService=new UsersServiceImp();
		//通过接口来调用
		UsersServiceInter usersServiceInter=new UsersServiceImp();
		user=usersServiceInter.checkUser(user);
		if(user!=null)
		{
			List<Users> list=usersServiceInter.getUserList(user);
			request.getSession().setAttribute("userList", list);
			//合法，将user放入session以备后用
			request.getSession().setAttribute("userInfo", user);
			//System.out.println("loginok");
			return mapping.findForward("loginok");
		}else{
			return mapping.findForward("goLoginUi");
		}
		
	}
}